nelmio_cors:
  defaults:
    origin_regex: true
    allow_credentials: true
    allow_origin: ['*']
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
    paths:
        '^/api/':  # Toutes les routes commençant par /api
            allow_origin: ['https://hackapress.you-dev.fr']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']