nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["*"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["*"]
    expose_headers: ["*"]
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: [ "*" ]
      allow_headers: [ "*" ]
      allow_methods: [ "*" ]
      expose_headers: [ "*" ]