services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.local
    volumes:
      - db_data:/var/lib/msql:rw
      - ./var/mysql:/var/www/var
    ports:
      - "3640:3306"

  php:
      user: '${USER_ID}:${GROUP_ID}'
      build: ./docker/php
      volumes:
        - .:/var/www:delegated
      depends_on:
        - db

  nginx:
    build: ./docker/nginx
    ports:
     - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
     - php

  adminer:
    image: adminer:latest
    restart: always
    environment: 
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER:
    depends_on:
      - db
    ports:
      - "8082:8080"

volumes:
  db_data:
