services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.local
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./var/mysql:/var/www/var
    ports:
      - "3640:3306"

  php:
    user: '${USER_ID}:${GROUP_ID}'
    build: ./docker/php
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sf-hackapress.rule=Host(`sf-hackapress.you-dev.fr`)"
      - "traefik.http.routers.sf-hackapress.entrypoints=websecure"
      - "traefik.http.routers.sf-hackapress.tls.certresolver=letsencrypt"
      - "traefik.http.services.sf-hackapress.loadbalancer.server.port=80"

  web:
    image: nginx:latest
    container_name: sf-hackapress-nginx
    depends_on:
      - php
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - default
      
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer-hackapress.you-dev.fr`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

volumes:
  db_data:
