version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - net

  db:
    image: mysql:8.0
    container_name: hackapress-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackapress
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3333:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net

volumes:
  db_data:

networks:
  net:
    driver: bridge
