name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: execute ssh cmd
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/sf-hackapress
            git pull origin master
            composer install --optimize-autoloader
            php bin/console d:d:c --if-not-exists && php bin/console d:m:m --no-interaction --allow-no-migration
            php bin/console cache:clear --env=prod